### ISSUE TITLE
Модель для комнаты

### ISSUE THREAD

**Issue by WokinShopash** [DIHTMasters/DIHT#17]
Сделать django-модель для комнаты

**Comment by kalinochkind** [comment]
Что должно быть в комнате:

1. Название
2. Замок (one-to-one, nullable)
3. Группа ответственных
4. Параметры расписания (тоже будет какая-нибудь модель, наподобие washing.Parameters, nullable)
5. Есть ли белый список (сами списки можно хранить в одной таблице `[room_id, user_id]`, если true, то список белый, иначе черный)
6. Видна ли она на сайте (?)

Расписание для всех комнат можно хранить в одной таблице, `[room_id, user_id, start_time, end_time, is_unlocked_for_everyone (?)]`.
Второй вариант: `[room_id, user_id, start_time, is_unlocked_for_everyone (?)]` -- блоки фиксированного размера, размер задается в параметрах расписания

Если что-то забыл, дополняйте

**Comment by WokinShopash** [comment]
Видимо, мы стремимся к тому, чтобы стиралка была тоже Room, поэтому 4ое поле тоже как-нибудь обобщим.
5. И белый и черный есть. Способ хранения норм.
6. Пока давайте с точки зрения базы/админки думать, потом, видимо, стоит запилить странички для комнат с правилами и т.д. (кстати, правила можно добавить полем в комнату)

**Comment by kalinochkind** [comment]
Стиралка будет какой-то странной Room, потому что там другая логика записи и работы замков. И выглядит расписание по-другому. Проще оставить как есть, имхо.
5. У велокомнаты может быть и белый, и черный список одновременно? Если да, то черный есть всегда, а белые лежат в отдельной таблице и используются, если у комнаты стоит флаг

**Comment by WokinShopash** [comment]
На самом деле, хочется сделать все-таки общий интерфейс для всех комнат, поскольку общие функции все-таки есть (черный-белый списки, функция проверки пропуска в замке, которая переопределяется во всех наследниках).

**Comment by WokinShopash** [comment]
Кажется, просто нужно сделать базовую модель Room с общими параметрами/функциями и каждую комнату от нее унаследовать, кастомизируя логику. То есть, формально, каждая такая модель будет иметь один экземпляр в базе (кажется, нужна вот это штука - https://github.com/lazybird/django-solo)

**Comment by kalinochkind** [comment]
В чем тогда смысл модели вообще? Хардкодить проще в самом коде, чем в базе

**Comment by WokinShopash** [comment]
Так мы и не хардкодим в базе. Данные-то сами (расписания и их настройки) надо хранить => нужна модель

**Comment by kalinochkind** [comment]
Вторая версия

1. Название
2. Замок (one-to-one, nullable)
3. Группа ответственных
4. Параметры расписания (Если null, расписания нет)
5. Есть ли белый список
6. Нужно ли одобрение со стороны ответственных для простых пользователей


Расписание для всех комнат можно хранить в одной таблице, `[room_id, user_id, start_time, end_time, is_approved]`. Белый список хранится здесь же, вместо start_time и end_time стоит null.

Пользователей, которым владелец разрешил доступ на время своего бронирования, храним как `[interval_id, user_id]`.
Черный список хранится в `[room_id, user_id]`.

Комнаты со стиралками (2 штуки) будут в отдельной модели. Ее можно унаследовать от этой. А можно и не наследовать
