### ISSUE TITLE
Написать скриптик для сохранения/выкачки базы

### ISSUE THREAD

**Issue by WokinShopash** [DIHTMasters/DIHT#19]
В процессе переезда _могут_ сильно пострадать модели, связанные с юзерами (и не только), и джанговские миграции могут не спасти. Поэтому надо задумываться о том, чтобы при переезде сохранить старую базу и руками мигрануть на новую схему

**Comment by kalinochkind** [comment]
Чем плохо делать такие миграции на SQL в самой базе?

**Comment by WokinShopash** [comment]
Ничем. Про эти скрипты я и говорю

**Comment by kalinochkind** [comment]
Как мы их заранее напишем, не зная, какие миграции нам могут понадобиться?

**Comment by WokinShopash** [comment]
Пока никак. Поэтому в описании и есть фраза "надо задумываться". Короче, чтобы не забыли :)
