### ISSUE TITLE
Хеширование uidов

### ISSUE THREAD

**Issue by kalinochkind** [DIHTMasters/DIHT#46]
В базе хранится hash(hash(uid + SALT)), SALT — большая случайная строка, задается в settings и хранится на замках. От замка приходит hash(uid + SALT). В качестве hash можно взять, например, 100 раз повторенный sha256.

**Comment by nipnull** [comment]
Вопрос времени работы этого чуда. Надо учитывать время работы этого на слабых машинах, а не на серве.
Доп инфа по хешам: на md5 и sha1 есть коллизии, да. Но они остаются актуальными для сверки не битый ли файл (при скачивании его откуда-либо).
А в плане проверки на подмену сейчас остается sha256
