### ISSUE TITLE
Не пускать пользователя в комнату до того, как он принял правила

### ISSUE THREAD

**Issue by kalinochkind** [DIHTMasters/DIHT#48]

**Comment by kalinochkind** [comment]
1 - расписание, 2 - белый список, 3 - подтверждение

000 - пускаем всех
001 - пускаем после принятия правил (качалка)
010 - бред
011 - можно оставить заявку (велокомната)
100 - стиралка, кдс
101 - клуб
110 - хз
111 - хз

**Comment by kalinochkind** [comment]
Для гостей подтверждение есть везде

**Comment by WokinShopash** [comment]
> 100 - стиралка, кдс
> 101 - клуб
Разве у стиралки нет своих правил пользования, которые тоже надо принимать?

**Comment by nipnull** [comment]
Если я правильно понял логику, то кдс и стирку можно брать, если не занято уже. А для клуба надо получть одобрение ответственного.

**Comment by kalinochkind** [comment]
Да, у стиралки свои правила. Это для примера скорее
