### ISSUE TITLE
Возможность создавать UIDы, не привязанные к пользователям

### ISSUE THREAD

**Issue by kalinochkind** [DIHTMasters/DIHT#54]
Например, охрана, уборщицы. У каждого из них есть доступ к некоторому набору комнат

**Comment by WokinShopash** [comment]
Не лучше ли вшить их в саму пишку? Вроде говорилось, что с uid'ом Саши, например, так и будет, на случай отказа сайта.

**Comment by kalinochkind** [comment]
Вшитые тоже будут. Но не добавлять же туда всех уборщиц и охранников. Тем более, каждому доступен свой набор  комнат, и со временем они могут меняться.

**Comment by WokinShopash** [comment]
Просто я вангую ситуации, когда злая тетя-охранница вырывает с корнем замок  и громко орет матом на всю общагу

**Comment by nipnull** [comment]
Имхо: сделать 2 (максимум 3) карты вшитые, причем это должны быть не пропуска (пропуск можно потерять или испортить), а карты чисто для данной системы, которые лежат, например: у главы хоз сектора, у председателя, у коменды. А всех остальных уже через скрипт без зашитых uid, дабы была единая логика.
