### ISSUE TITLE
Скрипт для замка

### ISSUE THREAD

**Issue by kalinochkind** [DIHTMasters/DIHT#55]
Запрос от замка:
`POST /rooms/check_access/<ID замка>/<hash(uid)>`

Параметры:
`token=<token>`

ID (число) и токен (строка) задаются для каждого замка отдельно

hash выглядит так
```
def hash(pass_id):
    pass_id = pass_id.lower()
    pass_id += PASS_SALT
    for i in range(3):
        pass_id = hashlib.sha256(pass_id.encode()).hexdigest()
    return pass_id
```

`PASS_SALT` - строка, одинаковая для всех замков

Ответ от сервера: одна строка
INVALID - неизвестный UID
DENIED - доступ запрещен
GRANTED - доступ разрешен

Если uid забит в замке, и доступ разрешен независимо от сервера, нужно все равно отправить запрос, добавив POST-параметр `granted=1`

**Comment by nipnull** [comment]
range 3 - гуд.

есть реализация private pub для токена?
