### ISSUE TITLE
Редактирование описания мероприятия

### ISSUE THREAD

**Issue by WokinShopash** [DIHTMasters/DIHT#57]
Ответственный за мероприятие, если он не создатель мероприятия, не может редактировать описание.

**Comment by bixind** [comment]
Может тогда закрыть им доступ к остальной информации тоже, вроде даты?

**Comment by WokinShopash** [comment]
Да, надо открыть описание. Ответственный может менять все, кроме списка ответственных.

**Comment by bixind** [comment]
На данный момент никто не хранит создателя мероприятия, так что если он должен обладать большими правами, чем остальные ответственные, нужно это учесть при переделке мероприятий.
Или просто сказать, что менять мероприятия могут те же люди, что и создавать.

**Comment by bixind** [comment]
Так мне влить эти изменения?
