### ISSUE TITLE
Error 500 в случае заполнения контактной информации рандомным образом

### ISSUE THREAD

**Issue by WokinShopash** [DIHTMasters/DIHT#60]
При заполнении во все поля в профиле <"( сервер рушится при попытке в дальнейшем открыть этот профиль. Необходимо добавить валидацию на правильный ввод не только в номере телефона.

**Comment by kalinochkind** [comment]
Это уже исправлено

**Comment by WokinShopash** [comment]
ок, скорее на проверить было
