### ISSUE TITLE
Иногда пересчитывать количество денег у пользователя

### ISSUE THREAD

**Issue by kalinochkind** [DIHTMasters/DIHT#82]
1. Открываем юзера в админке, что-нибудь меняем
2. Кладем юзеру денег не через админку
3. Жмем сейв в админке

Будет закешировано неправильное количество денег

**Comment by bixind** [comment]
Мне кажется это можно делать при миграциях

**Comment by kalinochkind** [comment]
Миграции делаются редко. Это надо делать при каждой операции с деньгами, если не чаще

**Comment by kalinochkind** [comment]
Еще лучше бы убрать баланс из админки вообще

**Comment by sashalab** [comment]
Убери

**Comment by bixind** [comment]
вообще говоря такая же проблема будет и с очками роста, насколько я знаю

**Comment by bixind** [comment]
Да и вообще с чем угодно, если ты будешь через админку старую версию сохранять

**Comment by bixind** [comment]
Кстати говоря, я заметил, что кэширование денег сейчас плохо работает (в частности при удалении операции кэш не всегда обновляется), поэтому если мы его не выпилим, то его стоит попробовать переписать на процедуры бд.

**Comment by bixind** [comment]
fixed 665fbea6af42f07aca4c68eb8411a80b92fd5657
