### ISSUE TITLE
Колокольчик с уведомлениями

### ISSUE THREAD

**Issue by kalinochkind** [DIHTMasters/DIHT#88]
Нужен колокольчик как на гитхабе. Скорее всего, слева от имени в хедере. Если есть непрочитанные уведомления, на нем должна быть циферка с  их количеством. С телефона он не должен уходить под гамбургер, как все остальное, а должен оставаться рядом с ним. При нажатии показывается дропдаун или что-то подобное. Текст либо подгружается хтмлькой через xhr, либо собирается на клиенте из жсона (это я сам могу потом сделать, главное окошко показать)

**Comment by bixind** [comment]
Более-менее весь колольчик
